version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DATABASE: vibeplandb
            DB_USERNAME: root
            DB_PASSWORD: root

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: vibeplandb
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - dbdata:/var/lib/mysql
            - ./mysql/dump.sql:/docker-entrypoint-initdb.d/dump.sql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: pma
        restart: always
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root

volumes:
    dbdata:
