<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>VibePlan | Dashboard Report</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            font-size: 12px;
            padding: 20px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
        }

        .header h1 {
            font-size: 24px;
            margin-bottom: 5px;
        }

        .header p {
            font-size: 14px;
            color: #666;
        }

        .section {
            margin-bottom: 40px;
            page-break-inside: avoid;
        }

        .section h3 {
            font-size: 16px;
            border-bottom: 1px solid #ccc;
            padding-bottom: 5px;
            margin-bottom: 15px;
            color: #222;
        }

        .chart {
            width: 100%;
            max-height: 400px;
            object-fit: contain;
            border: 1px solid #ccc;
            padding: 10px;
            background: #f8f8f8;
        }

        .footer {
            position: fixed;
            bottom: 15px;
            width: 100%;
            text-align: center;
            font-size: 10px;
            color: #999;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>📊 VibePlan Dashboard Report</h1>
        <p>Generated on {{ \Carbon\Carbon::now()->format('Y-m-d H:i') }}</p>
    </div>

    <div class="section">
        <h3>1. Inventory Sales (Bar Chart)</h3>
        <img class="chart" src="{{ $charts['salesChart'] }}" alt="Inventory Sales">
    </div>

    <div class="section">
        <h3>2. Inventory Sales by Event</h3>
        <img class="chart" src="{{ $charts['salesByEventChart'] }}" alt="Sales by Event">
    </div>

    <div class="section">
        <h3>3. Monthly Revenue by Inventory Item</h3>
        <img class="chart" src="{{ $charts['monthlyRevenueChart'] }}" alt="Monthly Revenue">
    </div>

    <div class="section">
        <h3>4. Revenue by Event Type (Based on Payments)</h3>
        <img class="chart" src="{{ $charts['eventTypeRevenueChart'] }}" alt="Revenue by Event Type">
    </div>

    <div class="footer">
        &copy; {{ date('Y') }} VibePlan • Report generated by Admin
    </div>

</body>

</html>
